name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Trigger on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out repo

      - name: Copy docs/ to root
        run: |
          mkdir -p public
          cp -r docs/* public/  # Same as GitLab, but GitHub Pages needs 'docs/' or root files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Deploy from 'public/' (like GitLab)
